[unstable]
# cross compile core library for custom target
build-std = ["core", "compiler_builtins"]
build-std-features = ["compiler-builtins-mem"]

[build]
rustflags = ["-A", "dead_code", "-A", "unused_variables", "-A", "unused_unsafe", "-A", "unused_must_use", "-A", "unreachable_code", "-A", "unused_imports"]
# points to file in project root
target = "x86-unknown-bare_metal.json"