[package]
name = "kernel"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rlib = {path = "../rlib"}
anyhow = { version = "1.0", default-features = false }

[profile.release]
panic = "abort"
